safe: true
lsi: false
highlighter: rouge
source: .
#url: http://thinking.ameriwether.com
title: Thinking Considered Harmful
subtitle: The Technical Musings of Aaron Meriwether
author: Aaron Meriwether
email: me@ameriwether.com
gravatar: 5f8d06524206be02374e12248c4aca51
disqus: thinking-awirtz-com
excerpt_separator: <!--more-->
links: {
    Gists: {
        "https://gist.github.com/": {
            1239069: Run process in other X session,
            1311172: Evade AD password reset timer,
            8213727: Extract Symantec VIP Access key,
            8470353: Sync Google Drive and Dropbox,
        },
    },
    Repos: {
        "https://github.com/": {
            aaronmeriwether/blowfish.js: Blowfish with CBC in JS,
            aaronmeriwether/node-jsdoc-toolkit: JSDoc port for Node.js,
            aaronmeriwether/darwin-racoon-cisco-cert-fix: Patched OSX IPSEC VPN client,
            aaronmeriwether/libfb-bsd: Framebuffer access for FreeBSD,
            aaronmeriwether/SoftGC: Application-layer GC for Java,
            aaronmeriwether/java-1.7.0-sun-compat: JPackage compat for Sun JDK7,
        },
    },
    Links: {
        "": {
            "https://github.com/aaronmeriwether": GitHub,
            "https://www.facebook.com/awirtz": Facebook,
            "https://www.linkedin.com/in/meriwether": LinkedIn,
            "https://resume.ameriwether.com/": Resumé,
            "https://careers.stackoverflow.com/ameriwether": Careers 2.0,
        },
    },
}
